//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.Ressource.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        internal static string Aide {
            get {
                return ResourceManager.GetString("Aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        internal static string Allergie {
            get {
                return ResourceManager.GetString("Allergie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arachides et noix.
        /// </summary>
        internal static string ArachideNoix {
            get {
                return ResourceManager.GetString("ArachideNoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        internal static string Autre {
            get {
                return ResourceManager.GetString("Autre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculatrice Nutritionnelle.
        /// </summary>
        internal static string CalculatriceNutritionnelle {
            get {
                return ResourceManager.GetString("CalculatriceNutritionnelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholestérol.
        /// </summary>
        internal static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        internal static string Connecter {
            get {
                return ResourceManager.GetString("Connecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer le profil.
        /// </summary>
        internal static string CreerProfil {
            get {
                return ResourceManager.GetString("CreerProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle du cholestérol.
        /// </summary>
        internal static string CtrlCholecterol {
            get {
                return ResourceManager.GetString("CtrlCholecterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle glycémique.
        /// </summary>
        internal static string CtrlGlycemique {
            get {
                return ResourceManager.GetString("CtrlGlycemique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        internal static string DateNaissance {
            get {
                return ResourceManager.GetString("DateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabète.
        /// </summary>
        internal static string Diabete {
            get {
                return ResourceManager.GetString("Diabete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain musculaire.
        /// </summary>
        internal static string GainMusculaire {
            get {
                return ResourceManager.GetString("GainMusculaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain de poids.
        /// </summary>
        internal static string GainPoids {
            get {
                return ResourceManager.GetString("GainPoids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        internal static string Generer {
            get {
                return ResourceManager.GetString("Generer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gluten.
        /// </summary>
        internal static string Gluten {
            get {
                return ResourceManager.GetString("Gluten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haute/basse pression.
        /// </summary>
        internal static string HauteBassePression {
            get {
                return ResourceManager.GetString("HauteBassePression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        internal static string Imprimer {
            get {
                return ResourceManager.GetString("Imprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        internal static string Inscrire {
            get {
                return ResourceManager.GetString("Inscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose.
        /// </summary>
        internal static string Lactose {
            get {
                return ResourceManager.GetString("Lactose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste d&apos;épicerie.
        /// </summary>
        internal static string ListeEpicerie {
            get {
                return ResourceManager.GetString("ListeEpicerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masse (kg).
        /// </summary>
        internal static string Masse {
            get {
                return ResourceManager.GetString("Masse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu &amp; liste d&apos;épicerie.
        /// </summary>
        internal static string MenuEpicerie {
            get {
                return ResourceManager.GetString("MenuEpicerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe actuel.
        /// </summary>
        internal static string MotDePasse {
            get {
                return ResourceManager.GetString("MotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de personne.
        /// </summary>
        internal static string NbrPersonne {
            get {
                return ResourceManager.GetString("NbrPersonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        internal static string NomUtilisateur {
            get {
                return ResourceManager.GetString("NomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        internal static string NvMotDePasse {
            get {
                return ResourceManager.GetString("NvMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectifs.
        /// </summary>
        internal static string Objectif {
            get {
                return ResourceManager.GetString("Objectif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un menu existant.
        /// </summary>
        internal static string OuvrirMenu {
            get {
                return ResourceManager.GetString("OuvrirMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètre.
        /// </summary>
        internal static string Parametre {
            get {
                return ResourceManager.GetString("Parametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pâtes.
        /// </summary>
        internal static string Pate {
            get {
                return ResourceManager.GetString("Pate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période.
        /// </summary>
        internal static string Periode {
            get {
                return ResourceManager.GetString("Periode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perte de poids.
        /// </summary>
        internal static string PertePoids {
            get {
                return ResourceManager.GetString("PertePoids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poissons et fruits de mer.
        /// </summary>
        internal static string PoissonFruitMer {
            get {
                return ResourceManager.GetString("PoissonFruitMer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préférences.
        /// </summary>
        internal static string Preference {
            get {
                return ResourceManager.GetString("Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        internal static string Quantite {
            get {
                return ResourceManager.GetString("Quantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions alimentaires.
        /// </summary>
        internal static string RestrictionAlimentaire {
            get {
                return ResourceManager.GetString("RestrictionAlimentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille (cm).
        /// </summary>
        internal static string Taille {
            get {
                return ResourceManager.GetString("Taille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une semaine.
        /// </summary>
        internal static string UneSemaine {
            get {
                return ResourceManager.GetString("UneSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure.
        /// </summary>
        internal static string UniteMesure {
            get {
                return ResourceManager.GetString("UniteMesure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un jour.
        /// </summary>
        internal static string UnJour {
            get {
                return ResourceManager.GetString("UnJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un repas.
        /// </summary>
        internal static string UnRepas {
            get {
                return ResourceManager.GetString("UnRepas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végétalien.
        /// </summary>
        internal static string Vegetalien {
            get {
                return ResourceManager.GetString("Vegetalien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végétarien.
        /// </summary>
        internal static string Vegetarien {
            get {
                return ResourceManager.GetString("Vegetarien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viandes.
        /// </summary>
        internal static string Viande {
            get {
                return ResourceManager.GetString("Viande", resourceCulture);
            }
        }
    }
}
