//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreAide {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreAide() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreAide", typeof(FenetreAide).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout de plat.
        /// </summary>
        public static string AjoutPlat {
            get {
                return ResourceManager.GetString("AjoutPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculatrice.
        /// </summary>
        public static string Calculatrice {
            get {
                return ResourceManager.GetString("Calculatrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculatrice nutritionnelle.
        /// </summary>
        public static string CalculatriceNutritionnelle {
            get {
                return ResourceManager.GetString("CalculatriceNutritionnelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don.
        /// </summary>
        public static string Don {
            get {
                return ResourceManager.GetString("Don", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un don.
        /// </summary>
        public static string EnvoyerUnDon {
            get {
                return ResourceManager.GetString("EnvoyerUnDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Génération de menu.
        /// </summary>
        public static string GenerationMenu {
            get {
                return ResourceManager.GetString("GenerationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langage.
        /// </summary>
        public static string Langage {
            get {
                return ResourceManager.GetString("Langage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste d&apos;épicerie.
        /// </summary>
        public static string ListeEpicerie {
            get {
                return ResourceManager.GetString("ListeEpicerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu connecté.
        /// </summary>
        public static string MenuConnecte {
            get {
                return ResourceManager.GetString("MenuConnecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu principal.
        /// </summary>
        public static string MenuPrincipal {
            get {
                return ResourceManager.GetString("MenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil.
        /// </summary>
        public static string MonProfil {
            get {
                return ResourceManager.GetString("MonProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètre.
        /// </summary>
        public static string Parametre {
            get {
                return ResourceManager.GetString("Parametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SeConnecter {
            get {
                return ResourceManager.GetString("SeConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension.
        /// </summary>
        public static string Suspension {
            get {
                return ResourceManager.GetString("Suspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Aide.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos paramètres.
        /// </summary>
        public static string VosParametres {
            get {
                return ResourceManager.GetString("VosParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre liste d&apos;épicerie.
        /// </summary>
        public static string VotreListeEpicerie {
            get {
                return ResourceManager.GetString("VotreListeEpicerie", resourceCulture);
            }
        }
    }
}
