//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreCalculatriceNutritionnelle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreCalculatriceNutritionnelle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreCalculatriceNutritionnelle", typeof(FenetreCalculatriceNutritionnelle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre de recherche.
        /// </summary>
        public static string BarreRecherche {
            get {
                return ResourceManager.GetString("BarreRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breuvage.
        /// </summary>
        public static string Breuvage {
            get {
                return ResourceManager.GetString("Breuvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculatrice nutritionnelle.
        /// </summary>
        public static string CalculatriceNutritionnelle {
            get {
                return ResourceManager.GetString("CalculatriceNutritionnelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjeuner.
        /// </summary>
        public static string Dejeuner {
            get {
                return ResourceManager.GetString("Dejeuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déssert.
        /// </summary>
        public static string Dessert {
            get {
                return ResourceManager.GetString("Dessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée.
        /// </summary>
        public static string Entree {
            get {
                return ResourceManager.GetString("Entree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plat principaux.
        /// </summary>
        public static string PlatPrincipaux {
            get {
                return ResourceManager.GetString("PlatPrincipaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Calculatrice nutritionnelle.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur nutritive.
        /// </summary>
        public static string ValeurNutritive {
            get {
                return ResourceManager.GetString("ValeurNutritive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur nutritionnelles du plateau.
        /// </summary>
        public static string ValeurPlateau {
            get {
                return ResourceManager.GetString("ValeurPlateau", resourceCulture);
            }
        }
    }
}
