//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreAjoutPlatMembre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreAjoutPlatMembre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreAjoutPlatMembre", typeof(FenetreAjoutPlatMembre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une image.
        /// </summary>
        public static string AjoutImage {
            get {
                return ResourceManager.GetString("AjoutImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout de plats.
        /// </summary>
        public static string AjoutPlat {
            get {
                return ResourceManager.GetString("AjoutPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliments disponibles par groupe.
        /// </summary>
        public static string AlimentDispoGroupe {
            get {
                return ResourceManager.GetString("AlimentDispoGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition du plat.
        /// </summary>
        public static string CompositionPlat {
            get {
                return ResourceManager.GetString("CompositionPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition du plat (Aucun aliment).
        /// </summary>
        public static string CompositionVide {
            get {
                return ResourceManager.GetString("CompositionVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer l&apos;ajout.
        /// </summary>
        public static string ConfirmerAjout {
            get {
                return ResourceManager.GetString("ConfirmerAjout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un ou plusieurs champs invalides.
        /// </summary>
        public static string ErreurMessage {
            get {
                return ResourceManager.GetString("ErreurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string ErreurTitre {
            get {
                return ResourceManager.GetString("ErreurTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Dois débuter avec une lettre).
        /// </summary>
        public static string NomDebut {
            get {
                return ResourceManager.GetString("NomDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Caractères invalides).
        /// </summary>
        public static string NomInvalide {
            get {
                return ResourceManager.GetString("NomInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat.
        /// </summary>
        public static string NomPlat {
            get {
                return ResourceManager.GetString("NomPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Entre 2 et 50 caractères).
        /// </summary>
        public static string NomTaille {
            get {
                return ResourceManager.GetString("NomTaille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Plat déjà existant).
        /// </summary>
        public static string NomUnique {
            get {
                return ResourceManager.GetString("NomUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Champ vide).
        /// </summary>
        public static string NomVide {
            get {
                return ResourceManager.GetString("NomVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau plat a été correctement ajouté à la base de données..
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réussie.
        /// </summary>
        public static string SuccessTitre {
            get {
                return ResourceManager.GetString("SuccessTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Ajout de plat.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de plat.
        /// </summary>
        public static string TypePlat {
            get {
                return ResourceManager.GetString("TypePlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de plat (Aucun sélectionné).
        /// </summary>
        public static string TypeVide {
            get {
                return ResourceManager.GetString("TypeVide", resourceCulture);
            }
        }
    }
}
