//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreProfil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreProfil() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreProfil", typeof(FenetreProfil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Allergies --.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arachides et noix.
        /// </summary>
        public static string ArachidesNoix {
            get {
                return ResourceManager.GetString("ArachidesNoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Autres --.
        /// </summary>
        public static string Autre {
            get {
                return ResourceManager.GetString("Autre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer le profil.
        /// </summary>
        public static string BtnCreerLeProfil {
            get {
                return ResourceManager.GetString("BtnCreerLeProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier le profil.
        /// </summary>
        public static string BtnModifierLeProfil {
            get {
                return ResourceManager.GetString("BtnModifierLeProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholestérol.
        /// </summary>
        public static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle du cholestérol.
        /// </summary>
        public static string ControleCholesterol {
            get {
                return ResourceManager.GetString("ControleCholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle glycémique.
        /// </summary>
        public static string ControleGlycemique {
            get {
                return ResourceManager.GetString("ControleGlycemique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        public static string DateNaissanceGeneral {
            get {
                return ResourceManager.GetString("DateNaissanceGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance (Aucune date sélectionnée).
        /// </summary>
        public static string DateNaissanceVide {
            get {
                return ResourceManager.GetString("DateNaissanceVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabète.
        /// </summary>
        public static string Diabete {
            get {
                return ResourceManager.GetString("Diabete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données personnelles.
        /// </summary>
        public static string DonneesPersonnelles {
            get {
                return ResourceManager.GetString("DonneesPersonnelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain musculaire.
        /// </summary>
        public static string GainMusculaire {
            get {
                return ResourceManager.GetString("GainMusculaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain de poids.
        /// </summary>
        public static string GainPoids {
            get {
                return ResourceManager.GetString("GainPoids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gluten.
        /// </summary>
        public static string Gluten {
            get {
                return ResourceManager.GetString("Gluten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose.
        /// </summary>
        public static string Lactose {
            get {
                return ResourceManager.GetString("Lactose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masse (kg).
        /// </summary>
        public static string MasseGeneral {
            get {
                return ResourceManager.GetString("MasseGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masse (kg) (Aucune masse sélectionnée).
        /// </summary>
        public static string MasseVide {
            get {
                return ResourceManager.GetString("MasseVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte Nutritia a été créé avec succès!.
        /// </summary>
        public static string MessageCreationSucces {
            get {
                return ResourceManager.GetString("MessageCreationSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Félicitations.
        /// </summary>
        public static string MessageCreationTitre {
            get {
                return ResourceManager.GetString("MessageCreationTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un ou plusieurs champs invalides..
        /// </summary>
        public static string MessageModificationErreur {
            get {
                return ResourceManager.GetString("MessageModificationErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string MessageModificationErreurTitre {
            get {
                return ResourceManager.GetString("MessageModificationErreurTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte Nutritia a été modifié avec succès!.
        /// </summary>
        public static string MessageModificationSucces {
            get {
                return ResourceManager.GetString("MessageModificationSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réussite!.
        /// </summary>
        public static string MessageModificationSuccesTitre {
            get {
                return ResourceManager.GetString("MessageModificationSuccesTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe (lettres et chiffres).
        /// </summary>
        public static string MotPasseCaractereInvalide {
            get {
                return ResourceManager.GetString("MotPasseCaractereInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation (différent du mot de passe).
        /// </summary>
        public static string MotPasseConfirmationDifferent {
            get {
                return ResourceManager.GetString("MotPasseConfirmationDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation du mot de passe.
        /// </summary>
        public static string MotPasseConfirmationGeneral {
            get {
                return ResourceManager.GetString("MotPasseConfirmationGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MotPasseGeneral {
            get {
                return ResourceManager.GetString("MotPasseGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe (Entre 2 et 10 caractères).
        /// </summary>
        public static string MotpasseLongueur {
            get {
                return ResourceManager.GetString("MotpasseLongueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe (Champ vide).
        /// </summary>
        public static string MotPasseVide {
            get {
                return ResourceManager.GetString("MotPasseVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom (- &apos; et lettres seulement).
        /// </summary>
        public static string NomCaractereInvalide {
            get {
                return ResourceManager.GetString("NomCaractereInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom (Doit débuter avec une lettre).
        /// </summary>
        public static string NomDebutInvalide {
            get {
                return ResourceManager.GetString("NomDebutInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string NomGeneral {
            get {
                return ResourceManager.GetString("NomGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom (Entre 1 et 25 caractères).
        /// </summary>
        public static string NomLongueur {
            get {
                return ResourceManager.GetString("NomLongueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom (Champ vide).
        /// </summary>
        public static string NomVide {
            get {
                return ResourceManager.GetString("NomVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Objectifs --.
        /// </summary>
        public static string Objectifs {
            get {
                return ResourceManager.GetString("Objectifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectifs et Préférences.
        /// </summary>
        public static string ObjectifsPreferences {
            get {
                return ResourceManager.GetString("ObjectifsPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pâtes.
        /// </summary>
        public static string Pates {
            get {
                return ResourceManager.GetString("Pates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perte de poids.
        /// </summary>
        public static string PertePoids {
            get {
                return ResourceManager.GetString("PertePoids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poissons et fruits de mer.
        /// </summary>
        public static string PoissonFruitMer {
            get {
                return ResourceManager.GetString("PoissonFruitMer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Préférences --.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom (- &apos; et lettres seulement).
        /// </summary>
        public static string PrenomCaractereInvalide {
            get {
                return ResourceManager.GetString("PrenomCaractereInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom (Dois débuter avec une lettre).
        /// </summary>
        public static string PrenomDebutInvalide {
            get {
                return ResourceManager.GetString("PrenomDebutInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string PrenomGeneral {
            get {
                return ResourceManager.GetString("PrenomGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom (Entre 1 et 25 caractères).
        /// </summary>
        public static string PrenomLongueur {
            get {
                return ResourceManager.GetString("PrenomLongueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom (Champ vide).
        /// </summary>
        public static string PrenomVide {
            get {
                return ResourceManager.GetString("PrenomVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haute/basse pression.
        /// </summary>
        public static string Pression {
            get {
                return ResourceManager.GetString("Pression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions alimentaires.
        /// </summary>
        public static string RestrictionsAlimentaires {
            get {
                return ResourceManager.GetString("RestrictionsAlimentaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille (cm).
        /// </summary>
        public static string TailleGeneral {
            get {
                return ResourceManager.GetString("TailleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille (cm) (Aucune taille sélectionnée).
        /// </summary>
        public static string TailleVide {
            get {
                return ResourceManager.GetString("TailleVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Modification Profil.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Création de profil.
        /// </summary>
        public static string TitreCreation {
            get {
                return ResourceManager.GetString("TitreCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur (lettre et chiffres).
        /// </summary>
        public static string UsernameCaractereInvalide {
            get {
                return ResourceManager.GetString("UsernameCaractereInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string UsernameGeneral {
            get {
                return ResourceManager.GetString("UsernameGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur (Entre 2 et 15 caractères).
        /// </summary>
        public static string UsernameLongueur {
            get {
                return ResourceManager.GetString("UsernameLongueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur (nom déjà utilisé).
        /// </summary>
        public static string UsernameUnique {
            get {
                return ResourceManager.GetString("UsernameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur (Champ vide).
        /// </summary>
        public static string UsernameVide {
            get {
                return ResourceManager.GetString("UsernameVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végétalien.
        /// </summary>
        public static string Vegetalien {
            get {
                return ResourceManager.GetString("Vegetalien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végétarien.
        /// </summary>
        public static string Vegetarien {
            get {
                return ResourceManager.GetString("Vegetarien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viandes.
        /// </summary>
        public static string Viandes {
            get {
                return ResourceManager.GetString("Viandes", resourceCulture);
            }
        }
    }
}
