//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreConnexion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreConnexion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreConnexion", typeof(FenetreConnexion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez été banni(e), veuillez contacter un administrateur..
        /// </summary>
        public static string Bannissement {
            get {
                return ResourceManager.GetString("Bannissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion impossible.
        /// </summary>
        public static string ConnexionImpossible {
            get {
                return ResourceManager.GetString("ConnexionImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez-vous déjà un compte Nutritia? Cliquez ci-bas pour vous inscrire et créer un compte Nutritia.
        /// </summary>
        public static string InfoTexte {
            get {
                return ResourceManager.GetString("InfoTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string Inscrire {
            get {
                return ResourceManager.GetString("Inscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MotPasse {
            get {
                return ResourceManager.GetString("MotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe éronné.
        /// </summary>
        public static string MotPasseErreur {
            get {
                return ResourceManager.GetString("MotPasseErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe (Champ vide).
        /// </summary>
        public static string MotPasseVide {
            get {
                return ResourceManager.GetString("MotPasseVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string NomUtilisateur {
            get {
                return ResourceManager.GetString("NomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur (Champ vide).
        /// </summary>
        public static string NomUtilisateurVide {
            get {
                return ResourceManager.GetString("NomUtilisateurVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Connexion.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur non-existant.
        /// </summary>
        public static string UtilisateurNonExistant {
            get {
                return ResourceManager.GetString("UtilisateurNonExistant", resourceCulture);
            }
        }
    }
}
