//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreGenerateurMenus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreGenerateurMenus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreGenerateurMenus", typeof(FenetreGenerateurMenus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les images des plats ?.
        /// </summary>
        public static string AfficherImage {
            get {
                return ResourceManager.GetString("AfficherImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un déjeuner.
        /// </summary>
        public static string Dejeuner {
            get {
                return ResourceManager.GetString("Dejeuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un diner/souper.
        /// </summary>
        public static string DinerSouper {
            get {
                return ResourceManager.GetString("DinerSouper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        public static string Generer {
            get {
                return ResourceManager.GetString("Generer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations préalables à la génération.
        /// </summary>
        public static string InfoGeneration {
            get {
                return ResourceManager.GetString("InfoGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrédients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un jour.
        /// </summary>
        public static string Jour {
            get {
                return ResourceManager.GetString("Jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste d&apos;épicerie.
        /// </summary>
        public static string ListeEpicerie {
            get {
                return ResourceManager.GetString("ListeEpicerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un menu existant.
        /// </summary>
        public static string OuvrirMenu {
            get {
                return ResourceManager.GetString("OuvrirMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période :.
        /// </summary>
        public static string Periode {
            get {
                return ResourceManager.GetString("Periode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnes :.
        /// </summary>
        public static string Personnes {
            get {
                return ResourceManager.GetString("Personnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une semaine.
        /// </summary>
        public static string Semaine {
            get {
                return ResourceManager.GetString("Semaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breuvage.
        /// </summary>
        public static string SeparateurBreuvage {
            get {
                return ResourceManager.GetString("SeparateurBreuvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjeuner.
        /// </summary>
        public static string SeparateurDejeuner {
            get {
                return ResourceManager.GetString("SeparateurDejeuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déssert.
        /// </summary>
        public static string SeparateurDessert {
            get {
                return ResourceManager.GetString("SeparateurDessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée.
        /// </summary>
        public static string SeparateurEntree {
            get {
                return ResourceManager.GetString("SeparateurEntree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour.
        /// </summary>
        public static string SeparateurJour {
            get {
                return ResourceManager.GetString("SeparateurJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plat principal.
        /// </summary>
        public static string SeparateurPlatPrincipal {
            get {
                return ResourceManager.GetString("SeparateurPlatPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi des plats non admissibles.
        /// </summary>
        public static string SuiviNonAdmissible {
            get {
                return ResourceManager.GetString("SuiviNonAdmissible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Génération de menus.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez remplir la section Informations préalables à la génération et appuyer sur le bouton Générer pour générer un menu. Lors de l&apos;appuie sur le bouton, le menu apparaîtra..
        /// </summary>
        public static string TooltipNonAdmissible {
            get {
                return ResourceManager.GetString("TooltipNonAdmissible", resourceCulture);
            }
        }
    }
}
