//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreVote {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreVote() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreVote", typeof(FenetreVote).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string Confirmer {
            get {
                return ResourceManager.GetString("Confirmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divin.
        /// </summary>
        public static string Divin {
            get {
                return ResourceManager.GetString("Divin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais.
        /// </summary>
        public static string Mauvais {
            get {
                return ResourceManager.GetString("Mauvais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moyen.
        /// </summary>
        public static string Moyen {
            get {
                return ResourceManager.GetString("Moyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passable.
        /// </summary>
        public static string Passable {
            get {
                return ResourceManager.GetString("Passable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle note donneriez-vous à ce plat ?.
        /// </summary>
        public static string QuelleNote {
            get {
                return ResourceManager.GetString("QuelleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succulent.
        /// </summary>
        public static string Succulent {
            get {
                return ResourceManager.GetString("Succulent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Voter.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
    }
}
