//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreGestionRepertoire {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreGestionRepertoire() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreGestionRepertoire", typeof(FenetreGestionRepertoire).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout.
        /// </summary>
        public static string Ajout {
            get {
                return ResourceManager.GetString("Ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;un aliment.
        /// </summary>
        public static string AjoutAliment {
            get {
                return ResourceManager.GetString("AjoutAliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter l&apos;aliment.
        /// </summary>
        public static string AjouterAliment {
            get {
                return ResourceManager.GetString("AjouterAliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une image.
        /// </summary>
        public static string AjouterImage {
            get {
                return ResourceManager.GetString("AjouterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;un plat / breuvage.
        /// </summary>
        public static string AjoutPlatBreuvage {
            get {
                return ResourceManager.GetString("AjoutPlatBreuvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliment.
        /// </summary>
        public static string Aliment {
            get {
                return ResourceManager.GetString("Aliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliments disponibles par groupe.
        /// </summary>
        public static string AlimentDispoGroupe {
            get {
                return ResourceManager.GetString("AlimentDispoGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie alimentaire.
        /// </summary>
        public static string CategorieAlimentaire {
            get {
                return ResourceManager.GetString("CategorieAlimentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie alimentaire (Aucun de sélectionné).
        /// </summary>
        public static string CategorieVide {
            get {
                return ResourceManager.GetString("CategorieVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholestérol (mg).
        /// </summary>
        public static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition du plat.
        /// </summary>
        public static string CompositionPlat {
            get {
                return ResourceManager.GetString("CompositionPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition du plat (Aucun aliment).
        /// </summary>
        public static string CompositionVide {
            get {
                return ResourceManager.GetString("CompositionVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer l&apos;ajout.
        /// </summary>
        public static string ConfirmerAjout {
            get {
                return ResourceManager.GetString("ConfirmerAjout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la modification.
        /// </summary>
        public static string ConfirmerModification {
            get {
                return ResourceManager.GetString("ConfirmerModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Énergie (calories).
        /// </summary>
        public static string Energie {
            get {
                return ResourceManager.GetString("Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un ou plusieurs champs invalides.
        /// </summary>
        public static string ErreurMessage {
            get {
                return ResourceManager.GetString("ErreurMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string ErreurTitre {
            get {
                return ResourceManager.GetString("ErreurTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibres (g).
        /// </summary>
        public static string Fibre {
            get {
                return ResourceManager.GetString("Fibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des aliments et plats.
        /// </summary>
        public static string GestionAlimentPlat {
            get {
                return ResourceManager.GetString("GestionAlimentPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucides (g).
        /// </summary>
        public static string Glucide {
            get {
                return ResourceManager.GetString("Glucide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lipides (g).
        /// </summary>
        public static string Lipide {
            get {
                return ResourceManager.GetString("Lipide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure de la portion (1 à 500).
        /// </summary>
        public static string MesureBorne {
            get {
                return ResourceManager.GetString("MesureBorne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure de la portion (entier numérique).
        /// </summary>
        public static string MesureInvalide {
            get {
                return ResourceManager.GetString("MesureInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure de la portion.
        /// </summary>
        public static string MesurePortion {
            get {
                return ResourceManager.GetString("MesurePortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure de la portion (Champ vide).
        /// </summary>
        public static string MesureVide {
            get {
                return ResourceManager.GetString("MesureVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification d&apos;un aliment.
        /// </summary>
        public static string ModificationAliment {
            get {
                return ResourceManager.GetString("ModificationAliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification d&apos;un plat / breuvage.
        /// </summary>
        public static string ModificationPlatBreuvage {
            get {
                return ResourceManager.GetString("ModificationPlatBreuvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier l&apos;aliment.
        /// </summary>
        public static string ModifierAliment {
            get {
                return ResourceManager.GetString("ModifierAliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;aliment.
        /// </summary>
        public static string NomAliment {
            get {
                return ResourceManager.GetString("NomAliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;aliment (Dois débuter avec une lettre).
        /// </summary>
        public static string NomAlimentDebut {
            get {
                return ResourceManager.GetString("NomAlimentDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;aliment (Charactères invalides).
        /// </summary>
        public static string NomAlimentInvalide {
            get {
                return ResourceManager.GetString("NomAlimentInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;aliment (Entre 1 et 50 caractères).
        /// </summary>
        public static string NomAlimentTaille {
            get {
                return ResourceManager.GetString("NomAlimentTaille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;aliment (Aliment déjà existant).
        /// </summary>
        public static string NomAlimentUnique {
            get {
                return ResourceManager.GetString("NomAlimentUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;aliment (Champ vide).
        /// </summary>
        public static string NomAlimentVide {
            get {
                return ResourceManager.GetString("NomAlimentVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat.
        /// </summary>
        public static string NomPlat {
            get {
                return ResourceManager.GetString("NomPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Dois débuter avec une lettre).
        /// </summary>
        public static string NomPlatDebut {
            get {
                return ResourceManager.GetString("NomPlatDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Charactères invalides).
        /// </summary>
        public static string NomPlatInvalide {
            get {
                return ResourceManager.GetString("NomPlatInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Entre 2 et 50 caractères).
        /// </summary>
        public static string NomPlatTaille {
            get {
                return ResourceManager.GetString("NomPlatTaille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Plat déjà existant.
        /// </summary>
        public static string NomPlatUnique {
            get {
                return ResourceManager.GetString("NomPlatUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du plat (Champ vide).
        /// </summary>
        public static string NomPlatVide {
            get {
                return ResourceManager.GetString("NomPlatVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plat / Breuvage.
        /// </summary>
        public static string PlatBreuvage {
            get {
                return ResourceManager.GetString("PlatBreuvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protéines (g).
        /// </summary>
        public static string Proteine {
            get {
                return ResourceManager.GetString("Proteine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un aliment.
        /// </summary>
        public static string RechercherAliment {
            get {
                return ResourceManager.GetString("RechercherAliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un aliment (Aucun trouvé).
        /// </summary>
        public static string RechercherAlimentAucun {
            get {
                return ResourceManager.GetString("RechercherAlimentAucun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un plat.
        /// </summary>
        public static string RechercherPlat {
            get {
                return ResourceManager.GetString("RechercherPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un plat (Aucun trouvé).
        /// </summary>
        public static string RechercherPlatAucun {
            get {
                return ResourceManager.GetString("RechercherPlatAucun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium (mg).
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouvel aliment a été correctement ajouté à la base de données..
        /// </summary>
        public static string SuccessAjoutAlimentMessage {
            get {
                return ResourceManager.GetString("SuccessAjoutAlimentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;aliment réussie.
        /// </summary>
        public static string SuccessAjoutAlimentTitre {
            get {
                return ResourceManager.GetString("SuccessAjoutAlimentTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau plat a été correctement ajouté à la base de données..
        /// </summary>
        public static string SuccessAjoutPlatMessage {
            get {
                return ResourceManager.GetString("SuccessAjoutPlatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout de plat réussie.
        /// </summary>
        public static string SuccessAjoutPlatTitre {
            get {
                return ResourceManager.GetString("SuccessAjoutPlatTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;aliment a été correctement modifié dans la base de données..
        /// </summary>
        public static string SuccessModifAlimentMessage {
            get {
                return ResourceManager.GetString("SuccessModifAlimentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification d&apos;aliment réussie.
        /// </summary>
        public static string SuccessModifAlimentTitre {
            get {
                return ResourceManager.GetString("SuccessModifAlimentTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le plat a été correctement modifié dans la base de données..
        /// </summary>
        public static string SuccessModifPlatMessage {
            get {
                return ResourceManager.GetString("SuccessModifPlatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification du plat réussie.
        /// </summary>
        public static string SuccessModifPlatTitre {
            get {
                return ResourceManager.GetString("SuccessModifPlatTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritia - Gestion aliments et plats.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de plat.
        /// </summary>
        public static string TypePlat {
            get {
                return ResourceManager.GetString("TypePlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de plat (Aucun sélectionné).
        /// </summary>
        public static string TypeVide {
            get {
                return ResourceManager.GetString("TypeVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure.
        /// </summary>
        public static string UniteMesure {
            get {
                return ResourceManager.GetString("UniteMesure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure (Aucune de sélectionnée).
        /// </summary>
        public static string UniteMesureVide {
            get {
                return ResourceManager.GetString("UniteMesureVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs nutritionnelles (Total irréel).
        /// </summary>
        public static string ValeurNutritionnelleIrreel {
            get {
                return ResourceManager.GetString("ValeurNutritionnelleIrreel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs nutritionnelles.
        /// </summary>
        public static string ValeurNutritionnelles {
            get {
                return ResourceManager.GetString("ValeurNutritionnelles", resourceCulture);
            }
        }
    }
}
