//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FenetreVotes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FenetreVotes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.FenetreVotes", typeof(FenetreVotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouté par.
        /// </summary>
        public static string AjoutePar {
            get {
                return ResourceManager.GetString("AjoutePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        public static string Aucune {
            get {
                return ResourceManager.GetString("Aucune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre de recherche.
        /// </summary>
        public static string BarreRecherche {
            get {
                return ResourceManager.GetString("BarreRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divin.
        /// </summary>
        public static string Divin {
            get {
                return ResourceManager.GetString("Divin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les plus populaires.
        /// </summary>
        public static string LesPlusPopulaires {
            get {
                return ResourceManager.GetString("LesPlusPopulaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les plus récents.
        /// </summary>
        public static string LesPlusRecents {
            get {
                return ResourceManager.GetString("LesPlusRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais.
        /// </summary>
        public static string Mauvais {
            get {
                return ResourceManager.GetString("Mauvais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moyen.
        /// </summary>
        public static string Moyen {
            get {
                return ResourceManager.GetString("Moyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de votes :.
        /// </summary>
        public static string NbrVotes {
            get {
                return ResourceManager.GetString("NbrVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passable.
        /// </summary>
        public static string Passable {
            get {
                return ResourceManager.GetString("Passable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un plat.
        /// </summary>
        public static string RechercherUnPlat {
            get {
                return ResourceManager.GetString("RechercherUnPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succulent.
        /// </summary>
        public static string Succulent {
            get {
                return ResourceManager.GetString("Succulent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter sur des plats.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les plats.
        /// </summary>
        public static string TousLesPlats {
            get {
                return ResourceManager.GetString("TousLesPlats", resourceCulture);
            }
        }
    }
}
