//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepter.
        /// </summary>
        public static string Accepter {
            get {
                return ResourceManager.GetString("Accepter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrateurs.
        /// </summary>
        public static string Administrateurs {
            get {
                return ResourceManager.GetString("Administrateurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Aide.
        /// </summary>
        public static string Aide {
            get {
                return ResourceManager.GetString("Aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        public static string Allergie {
            get {
                return ResourceManager.GetString("Allergie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an.
        /// </summary>
        public static string An {
            get {
                return ResourceManager.GetString("An", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  À propos.
        /// </summary>
        public static string APropos {
            get {
                return ResourceManager.GetString("APropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arachides et noix.
        /// </summary>
        public static string ArachideNoix {
            get {
                return ResourceManager.GetString("ArachideNoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        public static string Autre {
            get {
                return ResourceManager.GetString("Autre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculatrice Nutritionnelle.
        /// </summary>
        public static string CalculatriceNutritionnelle {
            get {
                return ResourceManager.GetString("CalculatriceNutritionnelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholestérol.
        /// </summary>
        public static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte.
        /// </summary>
        public static string Compte {
            get {
                return ResourceManager.GetString("Compte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string Connecter {
            get {
                return ResourceManager.GetString("Connecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer le profil.
        /// </summary>
        public static string CreerProfil {
            get {
                return ResourceManager.GetString("CreerProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle du cholestérol.
        /// </summary>
        public static string CtrlCholecterol {
            get {
                return ResourceManager.GetString("CtrlCholecterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle glycémique.
        /// </summary>
        public static string CtrlGlycemique {
            get {
                return ResourceManager.GetString("CtrlGlycemique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        public static string DateNaissance {
            get {
                return ResourceManager.GetString("DateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabète.
        /// </summary>
        public static string Diabete {
            get {
                return ResourceManager.GetString("Diabete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain musculaire.
        /// </summary>
        public static string GainMusculaire {
            get {
                return ResourceManager.GetString("GainMusculaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain de poids.
        /// </summary>
        public static string GainPoids {
            get {
                return ResourceManager.GetString("GainPoids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        public static string Generer {
            get {
                return ResourceManager.GetString("Generer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gluten.
        /// </summary>
        public static string Gluten {
            get {
                return ResourceManager.GetString("Gluten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haute/basse pression.
        /// </summary>
        public static string HauteBassePression {
            get {
                return ResourceManager.GetString("HauteBassePression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string Imprimer {
            get {
                return ResourceManager.GetString("Imprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string Inscrire {
            get {
                return ResourceManager.GetString("Inscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose.
        /// </summary>
        public static string Lactose {
            get {
                return ResourceManager.GetString("Lactose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste d&apos;épicerie.
        /// </summary>
        public static string ListeEpicerie {
            get {
                return ResourceManager.GetString("ListeEpicerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masse (kg).
        /// </summary>
        public static string Masse {
            get {
                return ResourceManager.GetString("Masse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu &amp; liste d&apos;épicerie.
        /// </summary>
        public static string MenuEpicerie {
            get {
                return ResourceManager.GetString("MenuEpicerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe actuel.
        /// </summary>
        public static string MotDePasse {
            get {
                return ResourceManager.GetString("MotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de personne.
        /// </summary>
        public static string NbrPersonne {
            get {
                return ResourceManager.GetString("NbrPersonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string NomUtilisateur {
            get {
                return ResourceManager.GetString("NomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        public static string NvMotDePasse {
            get {
                return ResourceManager.GetString("NvMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectifs.
        /// </summary>
        public static string Objectif {
            get {
                return ResourceManager.GetString("Objectif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un menu existant.
        /// </summary>
        public static string OuvrirMenu {
            get {
                return ResourceManager.GetString("OuvrirMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Paramètres.
        /// </summary>
        public static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pâtes.
        /// </summary>
        public static string Pate {
            get {
                return ResourceManager.GetString("Pate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période.
        /// </summary>
        public static string Periode {
            get {
                return ResourceManager.GetString("Periode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perte de poids.
        /// </summary>
        public static string PertePoids {
            get {
                return ResourceManager.GetString("PertePoids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poissons et fruits de mer.
        /// </summary>
        public static string PoissonFruitMer {
            get {
                return ResourceManager.GetString("PoissonFruitMer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préférences.
        /// </summary>
        public static string Preference {
            get {
                return ResourceManager.GetString("Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string Quantite {
            get {
                return ResourceManager.GetString("Quantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un membre.
        /// </summary>
        public static string RechercheMembre {
            get {
                return ResourceManager.GetString("RechercheMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions alimentaires.
        /// </summary>
        public static string RestrictionAlimentaire {
            get {
                return ResourceManager.GetString("RestrictionAlimentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Retour.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille (cm).
        /// </summary>
        public static string Taille {
            get {
                return ResourceManager.GetString("Taille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une semaine.
        /// </summary>
        public static string UneSemaine {
            get {
                return ResourceManager.GetString("UneSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité de mesure.
        /// </summary>
        public static string UniteMesure {
            get {
                return ResourceManager.GetString("UniteMesure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un jour.
        /// </summary>
        public static string UnJour {
            get {
                return ResourceManager.GetString("UnJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un repas.
        /// </summary>
        public static string UnRepas {
            get {
                return ResourceManager.GetString("UnRepas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végétalien.
        /// </summary>
        public static string Vegetalien {
            get {
                return ResourceManager.GetString("Vegetalien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végétarien.
        /// </summary>
        public static string Vegetarien {
            get {
                return ResourceManager.GetString("Vegetarien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viandes.
        /// </summary>
        public static string Viande {
            get {
                return ResourceManager.GetString("Viande", resourceCulture);
            }
        }
    }
}
