//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Don {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Don() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.Pages.Don", typeof(Don).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de sécurité.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * CSC invalide.
        /// </summary>
        public static string CodeInvalide {
            get {
                return ResourceManager.GetString("CodeInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string Confirmer {
            get {
                return ResourceManager.GetString("Confirmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration MM/YY.
        /// </summary>
        public static string ExpDate {
            get {
                return ResourceManager.GetString("ExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Expiration invalide.
        /// </summary>
        public static string ExpInvalide {
            get {
                return ResourceManager.GetString("ExpInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méthode de paiement disponible.
        /// </summary>
        public static string MethodePaiement {
            get {
                return ResourceManager.GetString("MethodePaiement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string Montant {
            get {
                return ResourceManager.GetString("Montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Nom invalide.
        /// </summary>
        public static string NomInvalide {
            get {
                return ResourceManager.GetString("NomInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du propriétaire.
        /// </summary>
        public static string NomProprietaire {
            get {
                return ResourceManager.GetString("NomProprietaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de carte.
        /// </summary>
        public static string NumCarte {
            get {
                return ResourceManager.GetString("NumCarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No Carte invalide.
        /// </summary>
        public static string NumInvalide {
            get {
                return ResourceManager.GetString("NumInvalide", resourceCulture);
            }
        }
    }
}
