//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutritia.UI.Ressources.Localisation.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuConnexion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuConnexion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nutritia.UI.Ressources.Localisation.Pages.MenuConnexion", typeof(MenuConnexion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement.
        /// </summary>
        public static string Chargement {
            get {
                return ResourceManager.GetString("Chargement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;hôte (ou adresse IP).
        /// </summary>
        public static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MotPasse {
            get {
                return ResourceManager.GetString("MotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la base de données.
        /// </summary>
        public static string NomBD {
            get {
                return ResourceManager.GetString("NomBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de session.
        /// </summary>
        public static string NomSession {
            get {
                return ResourceManager.GetString("NomSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string NomUtilisateur {
            get {
                return ResourceManager.GetString("NomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde.
        /// </summary>
        public static string Sauvegarde {
            get {
                return ResourceManager.GetString("Sauvegarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
    }
}
